/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScheduledRouteImport } from './routes/_app/scheduled'
import { Route as AppListsRouteImport } from './routes/_app/lists'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppCampaignsNewRouteImport } from './routes/_app/campaigns/new'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track/click'
import { Route as ApiPublicHooksProcessCampaignsRouteImport } from './routes/api/public/hooks/process-campaigns'
import { Route as ApiPublicTrackOpenIdRouteImport } from './routes/api/public/track/open.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduledRoute = AppScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AppRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track/click',
  path: '/api/public/track/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessCampaignsRoute =
  ApiPublicHooksProcessCampaignsRouteImport.update({
    id: '/api/public/hooks/process-campaigns',
    path: '/api/public/hooks/process-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackOpenIdRoute = ApiPublicTrackOpenIdRouteImport.update({
  id: '/api/public/track/open/$id',
  path: '/api/public/track/open/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lists': typeof AppListsRoute
  '/scheduled': typeof AppScheduledRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lists': typeof AppListsRoute
  '/scheduled': typeof AppScheduledRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lists': typeof AppListsRoute
  '/_app/scheduled': typeof AppScheduledRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open/$id': typeof ApiPublicTrackOpenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/lists'
    | '/scheduled'
    | '/settings'
    | '/templates'
    | '/campaigns/new'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/track/click'
    | '/api/public/track/open/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/lists'
    | '/scheduled'
    | '/settings'
    | '/templates'
    | '/campaigns/new'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/track/click'
    | '/api/public/track/open/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/lists'
    | '/_app/scheduled'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/campaigns/new'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/track/click'
    | '/api/public/track/open/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksProcessCampaignsRoute: typeof ApiPublicHooksProcessCampaignsRoute
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  ApiPublicTrackOpenIdRoute: typeof ApiPublicTrackOpenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduled': {
      id: '/_app/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AppScheduledRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/track/click': {
      id: '/api/public/track/click'
      path: '/api/public/track/click'
      fullPath: '/api/public/track/click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-campaigns': {
      id: '/api/public/hooks/process-campaigns'
      path: '/api/public/hooks/process-campaigns'
      fullPath: '/api/public/hooks/process-campaigns'
      preLoaderRoute: typeof ApiPublicHooksProcessCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open/$id': {
      id: '/api/public/track/open/$id'
      path: '/api/public/track/open/$id'
      fullPath: '/api/public/track/open/$id'
      preLoaderRoute: typeof ApiPublicTrackOpenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppListsRoute: typeof AppListsRoute
  AppScheduledRoute: typeof AppScheduledRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppListsRoute: AppListsRoute,
  AppScheduledRoute: AppScheduledRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksProcessCampaignsRoute: ApiPublicHooksProcessCampaignsRoute,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  ApiPublicTrackOpenIdRoute: ApiPublicTrackOpenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
